# Generated by Django 5.2.7 on 2025-11-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
