# Generated by Django 5.2.7 on 2025-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='subject_pdfs/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='subject_videos/'),
        ),
    ]
